export { default as Home } from './Home.vue';
export { default as About } from './About.vue';
export { default as Product } from './product/Product.vue';
export { default as Cart } from './Cart.vue';
export { default as NotFound } from './NotFound.vue';
export { default as Login } from './userId/Login.vue';
export { default as CreateAccount } from './userId/CreateAccount.vue';
export { default as ProductDetail } from './product/ProductDetail.vue';
export { default as Test } from './product/Test.vue';
